name: loan_calculator

version: "1.0.0"

dependencies:
  # Версии должны быть указаны точно, без диапазонов
  bloc: "9.0.0"
  collection: "1.19.1"
  decimal: "3.2.1"
  flutter:
    sdk: flutter
  flutter_bloc: "9.1.0"
  freezed_annotation: "3.0.0"
  jiffy: "6.3.2"
  rxdart: "0.28.0"

dev_dependencies:
  # Версии должны быть указаны точно, без диапазонов
  build_runner: "2.4.14"
  freezed: "3.0.6"
  json_serializable: "6.9.5"
  lintorium: ">=308.0.0"
  mocktail: "1.0.4"
  test: "1.25.15"
environment:
  # Версии должны быть указаны точно, без диапазонов
  sdk: "3.8.1"
  flutter: "3.32.4"

publish_to: "none"